version: 2

sources:
  - name: gz_raw_data
    schema: gz_raw_data
    description: greenweez raw data source 
    tables:
      - name: raw_gz_sales 
        identifier: raw_gz_sales
        description: vendas da greenweez 
        columns: 
          - name: date_date
            description: a data de compra
          - name: orders_id
            description: id de cada compra realizada / sendo único para cada compra
          - name: products_id
            description: id de cada produto / repetindo-se sempre que o mesmo produto é comprado
      - name: raw_gz_product
        identifier: raw_gz_product
      - name: raw_gz_ship
        identifier: raw_gz_ship
